model.playerList = [

    {
        userName: 'MasterLetters',
        age: 27,
        password: '123456',
        game: [{
                userName: 'MasterLetters',
                gameNumber: 1,
                date: '15/01/2022',
                word: 'bukse',
                attempts: 9,
                finished: true,
                gameDif: "fem",
            },
            {
                userName: 'MasterLetters',
                gameNumber: 2,
                date: '17/01/2022',
                word: 'hyasint',
                attempts: 7,
                finished: true,
                gameDif: "syv",
            },
            {
                userName: 'MasterLetters',
                gameNumber: 3,
                date: '10/03/2022',
                word: 'faktoring',
                attempts: 7,
                finished: true,
                gameDif: "ni",
            },
            {
                userName: 'MasterLetters',
                gameNumber: 4,
                date: '22/03/2022',
                word: 'varme',
                attempts: 6,
                finished: true,
                gameDif: "fem",
            },
            {
                userName: 'MasterLetters',
                gameNumber: 5,
                date: '12/03/2022',
                word: 'griseal',
                attempts: 4,
                finished: true,
                gameDif: "syv",
            },
            {
                userName: 'MasterLetters',
                gameNumber: 6,
                date: '10/04/2022',
                word: 'maskering',
                attempts: 10,
                finished: true,
                gameDif: "ni",
            },

        ],


    },

    {
        userName: 'TheWordBender',
        age: 26,
        password: 'password123',
        game: [{
                userName: 'TheWordBender',
                gameNumber: 1,
                date: '16/08/2022',
                word: 'brukbar',
                attempts: 9,
                finished: true,
                gameDif: "syv",
            },
            {
                userName: 'TheWordBender',
                gameNumber: 4,
                date: '19/09/2022',
                word: 'sverm',
                attempts: 7,
                finished: true,
                gameDif: "fem",
            },
            {
                userName: 'TheWordBender',
                gameNumber: 2,
                date: '17/08/2022',
                word: 'kabel',
                attempts: 7,
                finished: true,
                gameDif: "fem",
            },
            {
                userName: 'TheWordBender',
                gameNumber: 5,
                date: '26/09/2022',
                word: 'hipster',
                attempts: 12,
                finished: true,
                gameDif: "syv",
            },
            {
                userName: 'TheWordBender',
                gameNumber: 3,
                date: '17/09/2022',
                word: 'minstlønn',
                attempts: 8,
                finished: true,
                gameDif: "ni",
            },
            {
                userName: 'TheWordBender',
                gameNumber: 6,
                date: '27/09/2022',
                word: 'fartsdump',
                attempts: 14,
                finished: true,
                gameDif: "ni",
            },
        ],


    },

    {
        userName: 'WordWizzard',
        age: 23,
        password: 'winner',
        game: [{
                userName: 'WordWizzard',
                gameNumber: 1,
                date: '16/08/2022',
                word: 'skole',
                attempts: 3,
                finished: true,
                gameDif: "fem",
            },
            {
                userName: 'WordWizzard',
                gameNumber: 2,
                date: '18/08/2022',
                word: 'gråkval',
                attempts: 4,
                finished: true,
                gameDif: "syv",
            },
            {
                userName: 'MasterLetters',
                gameNumber: 2,
                date: '17/01/2022',
                word: 'bukostnad',
                attempts: 7,
                finished: true,
                gameDif: "ni",
            },
        ]

    },


]